---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Configure yum.conf
  template:
    src: yum.conf.j2
    dest: "{{ yumconf_config_file }}"
  tags:
    - yumconf_config
